KB_STORE = {
    "savings account": "A savings account is a deposit account that earns interest and is used to store money securely.",
    "current account": "A current account is a bank account designed for frequent transactions, mainly used by businesses.",
    "fixed deposit": "A fixed deposit is an investment where money is deposited for a fixed period at a predetermined interest rate.",
    "recurring deposit": "A recurring deposit allows customers to deposit a fixed amount regularly and earn interest over time.",
    "interest rate": "An interest rate is the percentage charged or earned on money over a period of time.",
    "compound interest": "Compound interest is interest calculated on both the principal and previously accumulated interest.",
    "simple interest": "Simple interest is calculated only on the principal amount.",
    "principal amount": "The principal amount is the original sum of money invested or borrowed.",
    "loan": "A loan is a sum of money borrowed that must be repaid with interest.",
    "home loan": "A home loan is a secured loan used to purchase residential property.",
    "personal loan": "A personal loan is an unsecured loan used for general personal expenses.",
    "car loan": "A car loan is a loan specifically used to finance the purchase of a vehicle.",
    "interest compounding": "Interest compounding refers to the process where interest is added to the principal, increasing future interest.",
    "emi": "Equated Monthly Installment (EMI) is the fixed monthly payment made to repay a loan.",
    "tenure": "Loan tenure is the duration over which the loan is to be repaid.",
    "credit score": "A credit score is a numerical representation of a person's creditworthiness.",
    "cibil score": "CIBIL score is a type of credit score used in India to assess credit risk.",
    "secured loan": "A secured loan requires collateral as security against the borrowed amount.",
    "unsecured loan": "An unsecured loan does not require collateral and is based on creditworthiness.",
    "collateral": "Collateral is an asset pledged as security for a loan.",
    "overdraft": "An overdraft allows account holders to withdraw more money than they have in their account.",
    "bank balance": "Bank balance is the amount of money available in a bank account.",
    "minimum balance": "Minimum balance is the least amount required to be maintained in a bank account.",
    "atm": "An ATM is a machine that allows customers to perform banking transactions without visiting a branch.",
    "debit card": "A debit card allows users to spend money directly from their bank account.",
    "credit card": "A credit card allows users to borrow money up to a limit for purchases.",
    "credit limit": "Credit limit is the maximum amount that can be borrowed using a credit card.",
    "billing cycle": "Billing cycle is the period between two credit card statements.",
    "due date": "Due date is the last date to pay a bill or EMI.",
    "late payment fee": "Late payment fee is a charge applied when payment is not made by the due date.",
    "net banking": "Net banking allows users to access banking services online.",
    "mobile banking": "Mobile banking enables banking transactions through a mobile application.",
    "upi": "UPI is a real-time payment system that allows instant money transfer between bank accounts.",
    "rtgs": "RTGS is a real-time gross settlement system used for high-value transactions.",
    "neft": "NEFT is a payment system used for transferring funds between banks.",
    "imps": "IMPS is an instant payment system for interbank fund transfer.",
    "cheque": "A cheque is a written order directing a bank to pay a specific amount.",
    "demand draft": "A demand draft is a prepaid financial instrument used for secure payments.",
    "bank statement": "A bank statement is a record of transactions in an account over a period.",
    "transaction": "A transaction is any financial activity in a bank account.",
    "deposit": "A deposit is money placed into a bank account.",
    "withdrawal": "A withdrawal is money taken out of a bank account.",
    "balance transfer": "Balance transfer is the process of moving debt from one account to another.",
    "mutual fund": "A mutual fund is an investment vehicle that pools money to invest in securities.",
    "sip": "Systematic Investment Plan (SIP) allows regular investment in mutual funds.",
    "equity": "Equity represents ownership in a company.",
    "stocks": "Stocks are shares that represent ownership in a company.",
    "share market": "The share market is where stocks are bought and sold.",
    "dividend": "Dividend is a portion of a company's profit distributed to shareholders.",
    "capital gain": "Capital gain is the profit earned from selling an asset.",
    "portfolio": "A portfolio is a collection of investments held by an individual.",
    "risk": "Risk refers to the possibility of financial loss.",
    "return": "Return is the profit earned from an investment.",
    "inflation": "Inflation is the rate at which prices of goods and services increase.",
    "liquidity": "Liquidity refers to how easily an asset can be converted into cash.",
    "asset": "An asset is anything of value owned by an individual.",
    "liability": "A liability is a financial obligation or debt.",
    "net worth": "Net worth is the difference between assets and liabilities.",
    "tax": "Tax is a compulsory financial charge imposed by the government.",
    "income tax": "Income tax is a tax levied on an individual's earnings.",
    "gst": "GST is a tax applied to goods and services in India.",
    "bank branch": "A bank branch is a physical location where banking services are provided.",
    "ifsc code": "IFSC code is a unique identifier for bank branches in India.",
    "account number": "An account number uniquely identifies a bank account.",
    "kyc": "KYC is a process used by banks to verify customer identity.",
    "pan card": "PAN card is a unique identification number issued for tax purposes in India.",
    "aadhaar": "Aadhaar is a unique identity number issued to residents of India.",
    "nominee": "A nominee is a person designated to receive assets in case of death.",
    "insurance": "Insurance is a financial product that provides protection against risks.",
    "life insurance": "Life insurance provides financial protection to beneficiaries after death.",
    "health insurance": "Health insurance covers medical expenses.",
    "premium": "Premium is the amount paid for an insurance policy.",
    "claim": "A claim is a request for payment under an insurance policy.",
    "fraud": "Fraud is wrongful or criminal deception for financial gain.",
    "cyber security": "Cyber security protects systems and data from digital attacks.",
    "phishing": "Phishing is a fraud attempt to steal sensitive information.",
    "otp": "OTP is a one-time password used for secure authentication.",
    "two factor authentication": "Two-factor authentication adds an extra layer of security.",
    "bank charges": "Bank charges are fees applied for banking services.",
    "processing fee": "Processing fee is charged for handling loan applications.",
    "foreclosure": "Foreclosure is early repayment of a loan.",
    "prepayment": "Prepayment is paying a loan before its due date.",
    "loan default": "Loan default occurs when a borrower fails to repay a loan.",
    "credit history": "Credit history is a record of a borrower's repayment behavior.",
    "financial planning": "Financial planning is managing finances to achieve goals.",
    "budget": "A budget is a plan for managing income and expenses.",
    "saving": "Saving is setting aside money for future use.",
    "investment": "Investment is allocating money to generate returns.",
    "retirement planning": "Retirement planning ensures financial security after retirement.",
    "pension": "Pension is a regular payment made after retirement.",
    "bond": "A bond is a fixed-income investment representing a loan to an entity.",
    "government bond": "A government bond is issued by the government to raise funds.",
    "treasury bill": "A treasury bill is a short-term government security.",
    "derivatives": "Derivatives are financial instruments based on underlying assets.",
    "future contract": "A futures contract is an agreement to buy or sell an asset at a future date.",
    "option contract": "An options contract gives the right but not obligation to trade an asset.",
    "market volatility": "Market volatility refers to price fluctuations in financial markets.",
    "bull market": "A bull market is a period of rising prices.",
    "bear market": "A bear market is a period of falling prices."
}