documents:
- path: https://jeetmajumder.vercel.app/
  enabled: true
chunking:
  similarity_threshold: 0.6
embedder:
  model: nvidia/nv-embedcode-7b-v1
retrieval:
  initial_pct: 0.8
  rerank_pct: 0.4
  mmr_pct: 0.3
  lambda_mult: 0.7
  min_chunk: 5
  reranker_model: nv-rerank-qa-mistral-4b:1
generation:
  llm_model: meta-llama/llama-4-scout-17b-16e-instruct
  temperature: 0.2
  max_output_tokens: 512
KB:
  kb_api_url: http://127.0.0.1:8000
  similarity_threshold: 0.3
  top_k_relevant: 3
